### ISSUE TITLE
Vivaldi browser  History recover

### ISSUE THREAD

**Issue by macoswk** [Shablone/history_trends_unlimited_to_firefox#1]
I extend my heartfelt gratitude for your selfless efforts, which enabled me to successfully recover 150,000 browsing history entries from a corrupted Vivaldi browser history file.
<img width="1018" alt="Screenshot - 2024-12-10 18 19 56" src="https://github.com/user-attachments/assets/a6775f5a-57d7-46c3-be92-330d07fb3355">

**Comment by Shablone** [comment]
I'm happy to hear that :)
